# Generated by Django 5.1.5 on 2025-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_experience', models.IntegerField()),
                ('commits', models.IntegerField()),
                ('projects_completed', models.IntegerField()),
                ('technologies_mastered', models.IntegerField()),
            ],
        ),
    ]
