# Generated by Django 5.1.5 on 2025-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
