# Generated by Django 5.1.5 on 2025-05-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stats_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Statstic',
        ),
    ]
