# Generated by Django 5.1.5 on 2025-05-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_stats_statstic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statstic',
            name='commits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statstic',
            name='projects_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statstic',
            name='technologies_mastered',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statstic',
            name='year_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
