# Generated by Django 5.1.5 on 2025-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_contact_name_contact_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
